---
- name: Download vagrant
  get_url: url={{ vagrant_url_rpm }} dest={{vagrant_tmp_rpm}} validate_certs={{ validate_certs }}

- name: Install vagrant for RedHat OS family
  yum: name={{vagrant_tmp_rpm}}
